-- Creates the product-service catalog table (aggregate root: Product).
-- Rollback: DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    price      NUMERIC(19, 4) NOT NULL,
    sku        VARCHAR(50) NOT NULL,
    status     VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version    BIGINT NOT NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku)
);
