spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: product_app
    password: product_app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  mvc:
    problemdetails:
      enabled: true

server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG