-- Creates the inventory-service stock table (aggregate root: Inventory).
-- product_id is a cross-service reference (no FK — database-per-service).
-- Rollback: DROP TABLE IF EXISTS inventories;

CREATE TABLE inventories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT NOT NULL,
    available_quantity  INTEGER NOT NULL,
    reserved_quantity   INTEGER NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version             BIGINT NOT NULL,
    CONSTRAINT uk_inventories_product_id UNIQUE (product_id),
    CONSTRAINT ck_inventories_available_quantity CHECK (available_quantity >= 0),
    CONSTRAINT ck_inventories_reserved_quantity CHECK (reserved_quantity >= 0)
);
